[package]
name = "bluez"
version = "0.1.3"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"
repository = "https://github.com/laptou/bluez-rs"
readme = "README.md"
description = "Control Bluetooth on Linux."
license = "MIT"
keywords = ["bluetooth", "bluez", "linux"]
exclude = ["example/*"]

[dependencies]
libc = "0.2"
thiserror = "1.0"
num-traits = "0.2"
num-derive = "0.3"
enumflags2 = "0.6.4"
enumflags2_derive = "0.6.4"
bytes = "0.5"
bitvec = "0.17"
futures = "0.3"
async-std = { version = "1.6", features = ["attributes"] }

[[bin]]
name = "discover"
path = "examples/discover.rs"
doc = false

[[bin]]
name = "list"
path = "examples/list.rs"
doc = false
